### ISSUE TITLE
Cannot Fine Module 'Clone'

### ISSUE THREAD

**Issue by B3L7** [Jerenaux/chunks_tutorial#1]
Followed the install for the splitter in the README but I get the following error when executing:

`internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'clone'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/b3l7/Repos/chunks_tutorial/splitter/splitmap.js:7:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
`

**Comment by Jerenaux** [comment]
I have updated package.json, now it should work.

**Comment by B3L7** [comment]
Ok. Went to the new version and got a new error:

```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'optimist'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/b3l7/Repos/chunks_tutorial/splitter/splitmap.js:100:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by Jerenaux** [comment]
Fixed :)

**Comment by B3L7** [comment]
That did it! Thanks.
